---
kind: pipeline
type: docker # 在 Docker Runner 中运行
name: default

steps:
  - name: build-image
    image: yusiwen/docker-dind:27.0.3
    pull: if-not-exists
    volumes:
      - name: dind-data
        path: /var/run
    environment:
      DOCKER_REGISTRY_USER:
        from_secret: docker_registry_user
      DOCKER_REGISTRY_PASSWORD:
        from_secret: docker_registry_password
      HTTP_PROXY:
        from_secret: http_proxy
      HTTPS_PROXY:
        from_secret: https_proxy
      NO_PROXY:
        from_secret: no_proxy
      CUSTOM_DNS:
        from_secret: custom_dns
    commands:
      - bash -c ./build.sh

  - name: deploy
    image: appleboy/drone-ssh
    pull: if-not-exists
    environment:
      VERSION: ${DRONE_TAG}
      DEPLOYMENT_LOCATION:
        from_secret: deployment_location
    settings:
      host:
        from_secret: deployment-ssh-host
      username:
        from_secret: deployment-ssh-user
      key:
        from_secret: deployment-ssh-key
      envs:
        - VERSION
        - DEPLOYMENT_LOCATION
      script:
        - cd $DEPLOYMENT_LOCATION && VERSION=$(echo $VERSION | tr -d 'v') docker compose up -d --wait --wait-timeout=200

trigger:
  event:
    - tag

volumes:
  - name: dind-data
    host:
      path: /root/git/myDocker/tools/docker/dind/run

node:
  node-tag: dev-private
