FROM python:3.8.18-slim-bullseye AS builder

WORKDIR /build
ADD . .

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i "s/deb\.debian\.org/mirrors\.aliyun\.com/g" /etc/apt/sources.list && \
    apt-get update && apt-get install tini

RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/ && \
    pip config set install.trusted-host mirrors.aliyun.com && \
    python -m venv .venv && \
    . .venv/bin/activate && \
    pip install -r requirements.txt && \
    pip install scrapyd==1.4.3 scrapyd-client==1.2.3 && \
    python setup.py bdist_egg

FROM python:3.8.18-slim-bullseye
LABEL maintainer=yusiwen@gmail.com

COPY --from=builder /usr/bin/tini /usr/bin/tini
COPY --from=builder /build/.venv/ /build/.venv/
COPY --from=builder /build/dist/app_monitor-1.0-py3.8.egg /scrapyd/eggs/app_monitor/app_monitor.egg
COPY ./scrapyd.conf /etc/scrapyd/scrapyd.conf

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bash", "-c", "source /build/.venv/bin/activate && scrapyd"]

EXPOSE 6800
