FROM python:3.8.18-slim-bullseye AS builder
LABEL maintainer=yusiwen@gmail.com

ADD ./requirements.txt /scrapy/requirements.txt
WORKDIR /scrapy
RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/ && \
    pip config set install.trusted-host mirrors.aliyun.com && \
    pip install -r requirements.txt

ADD . .
RUN python setup.py bdist_egg

FROM python:3.8.18-slim-bullseye
LABEL maintainer=yusiwen@gmail.com

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i "s/deb\.debian\.org/mirrors\.aliyun\.com/g" /etc/apt/sources.list && \
    apt update && apt install -y tini && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple/ && \
    pip config set install.trusted-host mirrors.aliyun.com && \
    pip install -r /requirements.txt
COPY ./scrapyd.conf /etc/scrapyd/scrapyd.conf
COPY --from=builder /scrapy/dist/app_monitor-1.0-py3.8.egg /scrapyd/eggs/app_monitor/app_monitor.egg

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["scrapyd"]

EXPOSE 6800
