---
services:
  app_monitor:
    image: yusiwen/app-monitor:${VERSION:-1.0.14}
    container_name: app_monitor
    restart: unless-stopped
    ports:
      - 127.0.0.1:6800:6800
    volumes:
      - ~/.app_monitor.cfg:/etc/scrapy/app_monitor.cfg

